package com.cser.play.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompanyInfo<M extends BaseCompanyInfo<M>> extends Model<M> implements IBean {

	public void setCompanyId(java.lang.Integer companyId) {
		set("company_id", companyId);
	}
	
	public java.lang.Integer getCompanyId() {
		return getInt("company_id");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
	}
	
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	public void setQrCode(java.lang.String qrCode) {
		set("qr_code", qrCode);
	}
	
	public java.lang.String getQrCode() {
		return getStr("qr_code");
	}

	public void setAdminUserId(java.lang.Integer adminUserId) {
		set("admin_user_id", adminUserId);
	}
	
	public java.lang.Integer getAdminUserId() {
		return getInt("admin_user_id");
	}

}
