package com.cser.play.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRewardTask<M extends BaseRewardTask<M>> extends Model<M> implements IBean {

	public void setTaskId(java.lang.Integer taskId) {
		set("task_id", taskId);
	}
	
	public java.lang.Integer getTaskId() {
		return getInt("task_id");
	}

	public void setTaskUserId(java.lang.Integer taskUserId) {
		set("task_user_Id", taskUserId);
	}
	
	public java.lang.Integer getTaskUserId() {
		return getInt("task_user_Id");
	}

	public void setTaskUserName(java.lang.String taskUserName) {
		set("task_user_name", taskUserName);
	}
	
	public java.lang.String getTaskUserName() {
		return getStr("task_user_name");
	}

	public void setTaskDesc(java.lang.String taskDesc) {
		set("task_desc", taskDesc);
	}
	
	public java.lang.String getTaskDesc() {
		return getStr("task_desc");
	}

	public void setNumberPeople(java.lang.Integer numberPeople) {
		set("number_people", numberPeople);
	}
	
	public java.lang.Integer getNumberPeople() {
		return getInt("number_people");
	}

	public void setAcceptNum(java.lang.Integer acceptNum) {
		set("accept_num", acceptNum);
	}
	
	public java.lang.Integer getAcceptNum() {
		return getInt("accept_num");
	}

	public void setReward(java.lang.Integer reward) {
		set("reward", reward);
	}
	
	public java.lang.Integer getReward() {
		return getInt("reward");
	}

	public void setTotalReward(java.lang.Integer totalReward) {
		set("total_reward", totalReward);
	}
	
	public java.lang.Integer getTotalReward() {
		return getInt("total_reward");
	}

	public void setImageUrl(java.lang.String imageUrl) {
		set("image_url", imageUrl);
	}
	
	public java.lang.String getImageUrl() {
		return getStr("image_url");
	}

	public void setTaskStatus(java.lang.String taskStatus) {
		set("task_status", taskStatus);
	}
	
	public java.lang.String getTaskStatus() {
		return getStr("task_status");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
