package com.cser.play.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGiftComment<M extends BaseGiftComment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setGiftId(java.lang.Integer giftId) {
		set("gift_id", giftId);
	}
	
	public java.lang.Integer getGiftId() {
		return getInt("gift_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}
	
	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public void setReplyUserId(java.lang.Integer replyUserId) {
		set("reply_user_id", replyUserId);
	}
	
	public java.lang.Integer getReplyUserId() {
		return getInt("reply_user_id");
	}

	public void setReplyNickName(java.lang.String replyNickName) {
		set("reply_nick_name", replyNickName);
	}
	
	public java.lang.String getReplyNickName() {
		return getStr("reply_nick_name");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}
	
	public java.lang.String getComment() {
		return getStr("comment");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
