package com.cser.play.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDealRecord<M extends BaseDealRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setDealTime(java.util.Date dealTime) {
		set("deal_time", dealTime);
	}
	
	public java.util.Date getDealTime() {
		return get("deal_time");
	}

	public void setDealType(java.lang.String dealType) {
		set("deal_type", dealType);
	}
	
	public java.lang.String getDealType() {
		return getStr("deal_type");
	}

	public void setDealDesc(java.lang.String dealDesc) {
		set("deal_desc", dealDesc);
	}
	
	public java.lang.String getDealDesc() {
		return getStr("deal_desc");
	}

	public void setAcceptUserId(java.lang.String acceptUserId) {
		set("accept_user_id", acceptUserId);
	}
	
	public java.lang.String getAcceptUserId() {
		return getStr("accept_user_id");
	}

	public void setAcceptUserName(java.lang.String acceptUserName) {
		set("accept_user_name", acceptUserName);
	}
	
	public java.lang.String getAcceptUserName() {
		return getStr("accept_user_name");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCategory(java.lang.String category) {
		set("category", category);
	}
	
	public java.lang.String getCategory() {
		return getStr("category");
	}

}
