package com.cser.play.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRewardTaskAccept<M extends BaseRewardTaskAccept<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTaskId(java.lang.Integer taskId) {
		set("task_id", taskId);
	}
	
	public java.lang.Integer getTaskId() {
		return getInt("task_id");
	}

	public void setAcceptUserId(java.lang.Integer acceptUserId) {
		set("accept_user_id", acceptUserId);
	}
	
	public java.lang.Integer getAcceptUserId() {
		return getInt("accept_user_id");
	}

	public void setAcceptUserName(java.lang.String acceptUserName) {
		set("accept_user_name", acceptUserName);
	}
	
	public java.lang.String getAcceptUserName() {
		return getStr("accept_user_name");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
