package com.cser.play.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSmsCode<M extends BaseSmsCode<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setCode(java.lang.Integer code) {
		set("code", code);
	}
	
	public java.lang.Integer getCode() {
		return getInt("code");
	}

	public void setExpireTime(java.lang.Long expireTime) {
		set("expire_time", expireTime);
	}
	
	public java.lang.Long getExpireTime() {
		return getLong("expire_time");
	}

}
