package com.cser.play.common.model;

import com.cser.play.common.model.base.BaseApplyList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ApplyList extends BaseApplyList<ApplyList> {
	
}
