package com.cser.play.common.model;

import com.cser.play.common.model.base.BaseCompanyAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CompanyAccount extends BaseCompanyAccount<CompanyAccount> {
	
}
