package com.cser.play.common.model;

import com.cser.play.common.model.base.BaseGiftLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GiftLike extends BaseGiftLike<GiftLike> {
	
}
