package com.cser.play.common.model;

import com.cser.play.common.model.base.BaseGiftComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GiftComment extends BaseGiftComment<GiftComment> {
	
}
