package com.cser.play.common.model;

import com.cser.play.common.model.base.BaseNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Notice extends BaseNotice<Notice> {
	
}
