package com.cser.play.common.model;

import com.cser.play.common.model.base.BasePayOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayOrder extends BasePayOrder<PayOrder> {
	
}
