package com.cser.play.common.model;

import com.cser.play.common.model.base.BaseSignSupplement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SignSupplement extends BaseSignSupplement<SignSupplement> {
	
}
