package com.cser.play.common.model;

import com.cser.play.common.model.base.BaseSignInInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SignInInfo extends BaseSignInInfo<SignInInfo> {
	
}
