package com.cser.play.common.model;

import com.cser.play.common.model.base.BaseSmsCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsCode extends BaseSmsCode<SmsCode> {
	
}
