package com.cser.play.common.model;

import com.cser.play.common.model.base.BaseSuggest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Suggest extends BaseSuggest<Suggest> {
	
}
